scalar Date

type Doctor {
  id: ID!
  name: String!
  lastname: String!
  yearsExperiences: Int!
  reviews: [Review!]!
  specialties: [String!]!
  ubications: [String!]!
  calendar: [Calendar!]
  imageNumber: Int!
  province: String!
  scoreAvg: Float!
}

type Review {
  username: String
  comment: String
  score: Int
}

type Calendar {
  id: ID
  date: String
  schedule: Times
}

type Times {
  time: String
  patient: ID
  note: String
  typeAppointment: String
}

input DoctorInput {
  name: String!
  lastname: String!
  yearsExperiences: Int!
  specialties: [String!]!
  ubications: [String!]!
}

input FindDoctorInput {
  fullname: String
  specialty: String
  province: String
}

input ReviewInput {
  username: String!
  comment: String!
  score: Int!
}

input CalendarInput {
  date: String!
  schedule: TimesInput!
}

input TimesInput {
  time: String!
  note: String!
  typeAppointment: String!
}
